#
# OAuth2
#
tokens:
    accessTokenUri: ${ACCESS_TOKEN_URI:}
    credentialsDirectory: ${CREDENTIALS_DIR:}

    token-configuration-list:
        - tokenId: customerLogin
          scopes:
              - uid
              - customer_service.all

security:
  oauth2:
    resource:
      # Get environment variable
      token-info-uri: ${TOKENINFO_URL}


upstreamRealm:
  tokenInfoUrl: ${TOKENINFO_URL}

realm:
  names:
    - "/services"
    - "/employees"
    - "/customers"
  userImpl:
    /employees: org.zalando.planb.provider.realms.impl.UpstreamUserRealm
    /customers: org.zalando.planb.provider.realms.impl.CustomerUserRealm

cassandra:
  keyspace: provider

# expose management endpoints on a different port
management:
  port: 7979
  security:
    enabled: false

hystrix:
  # https://github.com/Netflix/Hystrix/wiki/Configuration#ThreadPool
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: 32
      queueSizeRejectionThreshold: 32
  command:
    default:
      # https://github.com/Netflix/Hystrix/wiki/Configuration#CommandExecution
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
      # https://github.com/Netflix/Hystrix/wiki/Configuration#circuit-breaker
      circuitBreaker:
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 4000
        errorThresholdPercentage: 50
